import { slugify } from "@/lib/utils/text";
import { LeetCodeProblem, SolutionData, SupportedLanguage } from "@/types/api";

/**
 * Generate file path based on category structure
 */
export function generateFilePath(
  category: string,
  subcategory: string,
  problemNumber: string,
  title: string,
  isReadme: boolean = false
): string {
  // Create slug from title (e.g., "Two Sum" -> "two-sum")
  const slug = slugify(title);

  const folderName = `${problemNumber}-${slug}`;
  const fileName = isReadme ? "README.md" : `solution`;

  return `${category}/${subcategory}/${folderName}/${fileName}`;
}

/**
 * Get file extension based on language
 */
export function getFileExtension(language: string): string {
  const extensions: Record<string, string> = {
    typescript: "ts",
    javascript: "js",
    python: "py",
    java: "java",
    cpp: "cpp",
    go: "go",
  };

  return extensions[language] || "txt";
}

/**
 * Generate README content
 */
export function generateReadmeContent(
  problemData: LeetCodeProblem,
  solutionData: SolutionData
): string {
  const difficultyColors: Record<string, string> = {
    Easy: "5CB85C",
    Medium: "F0AD4E",
    Hard: "D9534F",
  };

  const languageColors: Record<string, string> = {
    typescript: "3178C6",
    javascript: "F7DF1E",
    python: "3776AB",
    java: "007396",
    cpp: "00599C",
    go: "00ADD8",
  };

  const difficultyColor = difficultyColors[problemData.difficulty] || "lightgrey";
  const languageColor = languageColors[solutionData.language] || "blue";

  const difficultyBadge = `https://img.shields.io/badge/${problemData.difficulty}-${difficultyColor}?style=flat-square`;
  const languageBadge = `https://img.shields.io/badge/${encodeURIComponent(
    solutionData.language
  )}-${languageColor}?style=flat-square&logo=${
    solutionData.language
  }&logoColor=white`;

  const date = new Date(solutionData.submissionDate);
  const formattedDate = date.toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });

  const topicsList = solutionData.topics || problemData.topicTags || [];
  const topics =
    topicsList.length > 0 ? topicsList.join(" • ") : "No Topics";

  return `# ${problemData.questionFrontendId}. ${problemData.title}

<table width="100%">
  <tr>
    <td width="150px"><b>Difficulty</b></td>
    <td>
      <img src="${difficultyBadge}" alt="${problemData.difficulty}">
    </td>
  </tr>
  <tr>
    <td><b>Language</b></td>
    <td>
      <img src="${languageBadge}" alt="${solutionData.language}">
    </td>
  </tr>
  <tr>
    <td><b>Topics</b></td>
    <td>${topics}</td>
  </tr>
  <tr>
    <td><b>Date</b></td>
    <td>${formattedDate}</td>
  </tr>
  <tr>
    <td><b>Problem Link</b></td>
    <td>
      <a href="${problemData.problemUrl}">
        View on LeetCode →
      </a>
    </td>
  </tr>
</table>

## 📋 Problem Description

${problemData.content}

---

## 💡 Solution Approach

${solutionData.approach}

---

## ⏱️ Complexity Analysis

| Metric | Complexity |
|:-------|:-----------|
| **Time** | \`${solutionData.timeComplexity}\` |
| **Space** | \`${solutionData.spaceComplexity}\` |

---

## 💻 Implementation

\`\`\`${solutionData.language}
${solutionData.solutionCode}
\`\`\`

---

<div align="center">
  <sub>Auto-generated by <a href="https://github.com/ijas9118/leetcode-github-sync-tool">LeetCode Github Sync Tool</a></sub>
</div>
`;
}

/**
 * Generate preview README content for the form preview
 */
export function generatePreviewReadme(
  problemData: LeetCodeProblem | null,
  formValues: {
    approach: string;
    timeComplexity: string;
    spaceComplexity: string;
    language: string;
    solutionCode: string;
  }
): string {
  if (!problemData) {
    const difficultyBadge =
      "https://img.shields.io/badge/Difficulty-Select_Problem-lightgrey?style=flat-square";
    const languageBadge = `https://img.shields.io/badge/Language-${encodeURIComponent(
      formValues.language || "typescript"
    )}-3178C6?style=flat-square&logo=${
      formValues.language || "typescript"
    }&logoColor=white`;

    return `# Preview Header

<table width="100%">
  <tr>
    <td width="150px"><b>Difficulty</b></td>
    <td>
      <img src="${difficultyBadge}" alt="Difficulty">
    </td>
  </tr>
  <tr>
    <td><b>Language</b></td>
    <td>
      <img src="${languageBadge}" alt="${formValues.language || "typescript"}">
    </td>
  </tr>
  <tr>
    <td><b>Topics</b></td>
    <td><i>Select a problem</i></td>
  </tr>
  <tr>
    <td><b>Date</b></td>
    <td>${new Date().toLocaleDateString("en-US", {
      month: "long",
      year: "numeric",
    })}</td>
  </tr>
</table>

## � Problem Description

*Fetch a problem to see the full description*

---

## 💡 Solution Approach

${formValues.approach || "*No approach provided yet*"}

---

## ⏱️ Complexity Analysis

| Metric | Complexity |
|:-------|:-----------|
| **Time** | \`${formValues.timeComplexity || "Not specified"}\` |
| **Space** | \`${formValues.spaceComplexity || "Not specified"}\` |

---

## 💻 Implementation

\`\`\`${formValues.language || "typescript"}
${formValues.solutionCode || "// Your solution code will appear here"}
\`\`\`

---

<div align="center">
  <sub>Auto-generated by <a href="https://github.com/ijas9118/leetcode-github-sync-tool">LeetCode Github Sync Tool</a></sub>
</div>
`;
  }

  // Map form values to SolutionData interface structure
  const solutionData: SolutionData = {
    problemNumber: problemData.questionFrontendId,
    problemTitle: problemData.title,
    problemSlug: problemData.titleSlug,
    problemUrl: problemData.problemUrl || "",
    problemStatement: problemData.content,
    examples: [],
    constraints: "",
    topics: problemData.topicTags,
    difficulty: problemData.difficulty,
    language: formValues.language as SupportedLanguage,
    solutionCode: formValues.solutionCode,
    approach: formValues.approach || "*No approach provided yet*",
    timeComplexity: formValues.timeComplexity,
    spaceComplexity: formValues.spaceComplexity,
    category: "arrays", // Placeholder
    subcategory: "other", // Placeholder
    submissionDate: new Date().toISOString(),
  };

  return generateReadmeContent(problemData, solutionData);
}
