import { slugify, stripHtml, truncateContent } from "@/lib/utils/text";
import { LeetCodeProblem, SolutionData, SupportedLanguage } from "@/types/api";

/**
 * Generate file path based on category structure
 */
export function generateFilePath(
  category: string,
  subcategory: string,
  problemNumber: string,
  title: string,
  isReadme: boolean = false
): string {
  // Create slug from title
  const slug = slugify(title);

  const folderName = `${problemNumber}-${slug}`;
  const fileName = isReadme ? "README.md" : `solution`;

  return `${category}/${subcategory}/${folderName}/${fileName}`;
}

/**
 * Get file extension based on language
 */
export function getFileExtension(language: string): string {
  const extensions: Record<string, string> = {
    typescript: "ts",
    javascript: "js",
    python: "py",
    java: "java",
    cpp: "cpp",
    go: "go",
  };

  return extensions[language] || "txt";
}

/**
 * Generate README content
 */
export function generateReadmeContent(
  problemData: LeetCodeProblem,
  solutionData: SolutionData
): string {
  const difficultyColor =
    {
      Easy: "brightgreen",
      Medium: "orange",
      Hard: "red",
    }[problemData.difficulty] || "lightgrey";

  const difficultyBadge = `![Difficulty](https://img.shields.io/badge/Difficulty-${problemData.difficulty}-${difficultyColor}?style=for-the-badge&logo=leetcode)`;
  const languageBadge = `![Language](https://img.shields.io/badge/Language-${encodeURIComponent(
    solutionData.language
  )}-blue?style=for-the-badge&logo=${solutionData.language})`;

  return `# ${problemData.questionFrontendId}. ${problemData.title}

<p align="center">
  <img src="https://cdn.simpleicons.org/leetcode/FFA116" width="50" alt="LeetCode Logo">
</p>

<p align="center">
  ${difficultyBadge}
  ${languageBadge}
</p>

## 📝 Problem Description

${truncateContent(stripHtml(problemData.content), 1000)}

[**View full problem on LeetCode**](${problemData.problemUrl})

---

## 💡 Solution Approach

${solutionData.approach}

### ⏱️ Complexity Analysis

| Complexity | Description |
| :--- | :--- |
| **Time** | \`${solutionData.timeComplexity}\` |
| **Space** | \`${solutionData.spaceComplexity}\` |

---

## 💻 Code

\`\`\`${solutionData.language}
${solutionData.solutionCode}
\`\`\`

---

> _Auto-generated by [LeetCode Github Sync Tool](https://github.com/ijas9118/leetcode-github-sync-tool)_
`;
}

/**
 * Generate preview README content for the form preview
 */
export function generatePreviewReadme(
  problemData: LeetCodeProblem | null,
  formValues: {
    approach: string;
    timeComplexity: string;
    spaceComplexity: string;
    language: string;
    solutionCode: string;
  }
): string {
  if (!problemData) {
    return `# Preview Header

<p align="center">
  <img src="https://cdn.simpleicons.org/leetcode/FFA116" width="50" alt="LeetCode Logo">
</p>

<p align="center">
  ![Difficulty](https://img.shields.io/badge/Difficulty-Select_Problem-lightgrey?style=for-the-badge&logo=leetcode)
  ![Language](https://img.shields.io/badge/Language-${encodeURIComponent(
    formValues.language || "typescript"
  )}-blue?style=for-the-badge&logo=${formValues.language || "typescript"})
</p>

## 📝 Problem Description

*Fetch a problem to see the full description*

---

## 💡 Solution Approach

${formValues.approach || "*No approach provided yet*"}

### ⏱️ Complexity Analysis

| Complexity | Description |
| :--- | :--- |
| **Time** | \`${formValues.timeComplexity || "Not specified"}\` |
| **Space** | \`${formValues.spaceComplexity || "Not specified"}\` |

## 💻 Code

\`\`\`${formValues.language || "typescript"}
${formValues.solutionCode || "// Your solution code will appear here"}
\`\`\`
`;
  }

  // Map form values to SolutionData interface structure
  const solutionData: SolutionData = {
    problemNumber: problemData.questionFrontendId,
    problemTitle: problemData.title,
    problemSlug: problemData.titleSlug,
    problemUrl: problemData.problemUrl || "",
    problemStatement: problemData.content,
    examples: [],
    constraints: "",
    topics: problemData.topicTags,
    difficulty: problemData.difficulty,
    language: formValues.language as SupportedLanguage,
    solutionCode: formValues.solutionCode,
    approach: formValues.approach || "*No approach provided yet*",
    timeComplexity: formValues.timeComplexity,
    spaceComplexity: formValues.spaceComplexity,
    category: "arrays", // Placeholder
    subcategory: "other", // Placeholder
    submissionDate: new Date().toISOString(),
  };

  return generateReadmeContent(problemData, solutionData);
}
